### ISSUE TITLE
tale 的aspnetcore 实现吗

### ISSUE THREAD

**Issue by newpost** [liuzhenyulive/iBlogs#5]

**Comment by liuzhenyulive** [comment]
哈哈  仁兄好眼力  还没发布呢  怎么看出来的?
前端用了Tale, 打算加上微信公众号,博客园,CSND等平台的统一推送管理,可以实现在在本地用MD写博客,用git提交后,做个钩子通知这个系统 ,然后自动推送道各个平台.

**Comment by liuzhenyulive** [comment]
自己学习瞎玩一下  也不知道能不能做出来
